- name: Launch Cloud VMs
  hosts: localhost
  tasks:
    - name: Launch VM 2
      os_server:
        image: CC-Ubuntu18.04-20201016
        name: xu.vm2
        key: ~/.ssh/domathnick.pub
        key_name: domathnick
        availability_zone: nova
        flavor: m1.small
        state: present
        network: CH-819381-net
        floating_ips: 129.114.25.83
        security_groups: ENABLE_HTTP_HTTPS,ENABLE_SSH,ENABLE_KAFKA_COUCHDB,667273fd-a67a-4ca2-8a68-3088220e6374,7e09e9fd-4971-49bb-bd55-9aa2fa149b16

- name: Launch Cloud VMs
  hosts: localhost
  tasks:
    - name: Launch VM 3
      os_server:
        image: CC-Ubuntu18.04-20201016
        name: xu.vm3
        key: ~/.ssh/domathnick.pub
        key_name: domathnick
        availability_zone: nova
        flavor: m1.small
        state: present
        network: CH-819381-net
        floating_ips: 129.114.25.202
        security_groups: ENABLE_HTTP_HTTPS,ENABLE_SSH,ENABLE_KAFKA_COUCHDB,667273fd-a67a-4ca2-8a68-3088220e6374,7e09e9fd-4971-49bb-bd55-9aa2fa149b16
