#####################################################
### Play 0: Setup Cloud VM
#####################################################
- name: "Play 0: Set up cloud VM"
  hosts: MyLocalVMs
  gather_facts: no

  tasks:
#  - include_tasks: playbook_delete_cloud_vms.yml
#  - include_tasks: playbook_create_cloud_vms.yml
#  - include_tasks: playbook_cleanup.yml
  - include_tasks: playbook_local_setup.yml
#  - pause:
#      minutes: 1

#####################################################
### Play 2: Install docker
#####################################################
- name: "Play 0: Set up cloud VM"
  gather_facts: no
  hosts: MyChameleonVMs       # my list of VMs on chosen cloud
  remote_user:  cc        # remote user is cc but change as appropriate

  tasks:
  - include_tasks: playbook_setup_cloud_vms.yml
  - include_tasks: playbook_install_docker.yml


#####################################################
### Install Kube
#####################################################
- name: "Play 0: Set up cloud VM"
  gather_facts: no
  hosts: MyChameleonVMs       # my list of VMs on chosen cloud
  remote_user:  cc        # remote user is cc but change as appropriate

  tasks:
  - include_tasks: playbook_install_kube.yml


#####################################################
### Play 2: Start Kube
#####################################################
- name: "Play 0: Set up cloud VM"
  gather_facts: no
  hosts: VM3             # my list of VMs on chosen cloud
  remote_user: cc        # remote user is cc but change as appropriate

  tasks:
  - include_tasks: playbook_start_kube.yml

#####################################################
### Play 2: Join Kube
#####################################################
- name: "Play 0: Set up cloud VM"
  gather_facts: no
  hosts: VM2                  # my list of VMs on chosen cloud
  remote_user: cc             # remote user is cc but change as appropriate

  tasks:
  - include_tasks: playbook_join_kube.yml

#####################################################
### Install cloudant
#####################################################
- name: "Play 0: Set up cloud VM"
  gather_facts: no
  hosts: VM3  
  remote_user: cc             # remote user is cc but change as appropriate

  tasks:
  - include_tasks: playbook_install_cloudant.yml

#####################################################
### Play 2: Install docker
#####################################################
- name: "Play 0: Set up cloud VM"
  gather_facts: no
  #  hosts: MyChameleonVMs  
  hosts: VM3                # my list of VMs on chosen cloud
  remote_user: cc             # remote user is cc but change as appropriate

  tasks:
  - include_tasks: playbook_run_docker_files.yml

#####################################################
### Play 2: Install couchdb
#####################################################
- name: "Play 0: Set up cloud VM"
  gather_facts: no
  hosts: VM2                  # my list of VMs on chosen cloud
  remote_user: cc             # remote user is cc but change as appropriate

  tasks:
  - include_tasks: playbook_install_couchdb.yml

#####################################################
### Play 3: Install docker
#####################################################
- name: "Play 0: Set up cloud VM"
  gather_facts: no
  hosts: VM3                  # my list of VMs on chosen cloud
  remote_user: cc             # remote user is cc but change as appropriate

  tasks:
  - include_tasks: playbook_kafka_setup.yml

