---
- name: Start Zookeeper
  ansible.builtin.shell:
    chdir: /home/kafka/
    cmd: bin/zookeeper-server-start.sh config/zookeeper.properties
- name: Start Kafka
  ansible.builtin.shell:
    chdir: /home/kafka/
    cmd: bin/kafka-server-start.sh config/server.properties
- name: Start consumer
  ansible.builtin.shell:
    chdir: /home/src/
    cmd: python3 consumer.py
...
